name: Build and Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build
        run: |
          npm ci
          npm run build

      - name: Prepare SSH key
        env:
          SSH_KEY: ${{ secrets.VPS_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          printf "%s\n" "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH connection 🔑
        run: |
          SSH_OPTS="-i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
          ssh $SSH_OPTS ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo '✅ Connected to VPS successfully!'"

      - name: Rsync build files to VPS
        run: |
          SSH_OPTS="-i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            --exclude='*.log' \
            -e "ssh $SSH_OPTS" ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:${{ secrets.VPS_TARGET_DIR }}

      - name: Restart app on VPS
        run: |
          SSH_OPTS="-i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"
          ssh $SSH_OPTS ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd ${{ secrets.VPS_TARGET_DIR }}
            npm ci --production
            sudo systemctl restart my-next-app.service
            sudo systemctl status my-next-app.service --no-pager
          EOF
